### ISSUE TITLE
how to install ?

### ISSUE THREAD

**Issue by hmyh1202** [LiuLabUB/SAPPER#2]
I used setup_w_cython.py to install, but always failed!

**Comment by hmyh1202** [comment]
there is no src/README in the git code

**Comment by hmyh1202** [comment]
![default](https://user-images.githubusercontent.com/18067365/48182978-287a2e80-e368-11e8-9981-02184401c8fe.png)

**Comment by taoliu** [comment]
It needs python version >= 3.6, numpy and cython for installation. If you are familiar with Docker, there is a compiled Docker image I just uploaded to Docker hub. Using this image will avoid all the trouble related to python environment, dependencies, operation system, and etc. 

https://hub.docker.com/r/fooliu/sapper
